#!/bin/sh
#
# Copyright 2004-2013 University of Zagreb.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#
# This work was supported in part by Croatian Ministry of Science
# and Technology through the research contract #IP-2003-143.
#

# $Id: imunes 110 2014-09-29 14:20:56Z denis $


SHELL=/bin/sh
export SHELL

ROOTDIR="."
LIBDIR=""

imunes=$ROOTDIR/$LIBDIR/imunes.tcl

batch_flag=0
prepare_flag=0
force_flag=0

for i; do
    if [ "$i" = "-f" ]; then
	force_flag=1
    fi
    if [ "$i" = "-p" ]; then
	prepare_flag=1
    fi
    if [ "$i" = "-b" ] || [ "$i" = "-batch" ] || [ "$i" = "-i" ] \
	|| [ "$i" = "-v" ] || [ "$i" = "-version" ]; then
	batch_flag=1
    fi
done

if [ $prepare_flag -eq 1 ]; then
    if [ $force_flag -eq 1 ]; then
	chflags -R noschg /var/imunes/vroot
	rm -fr /var/imunes/vroot
    fi
    cd $ROOTDIR/$LIBDIR
    sh scripts/prepare_vroot.sh
    exit 0
fi

if [ $batch_flag -eq 1 ]; then
    which tclsh8.6 2>&1 > /dev/null
    if [ $? -ne 0 ]; then
        echo "To run IMUNES, the package tclsh8.6 is required."
        exit 1
    fi

    if [ "`echo "package require ip" | tclsh8.6 2>&1`" != "" ]; then
        echo "To run IMUNES, the package tcllib is required."
        exit 1
    fi
    exec tclsh8.6 $imunes $*
else
    if [ -z "$DISPLAY" ]; then
        echo "To run IMUNES GUI, run IMUNES in X environment."
        exit 1
    fi

    which wish8.6 2>&1 > /dev/null
    if [ $? -ne 0 ]; then
        echo "To run IMUNES, the package wish8.6 is required."
        exit 1
    fi

    xerr=`echo "exit" | wish8.6 2>&1`;
    if [ -n "$xerr" ]; then
        echo "Cannot start imunes, problems with X:"
        echo "$xerr"
        exit 1
    fi

    if [ -n "`echo 'package require ip; exit' | wish8.6 2>&1`" ]; then
        echo "To run IMUNES, the package tcllib is required."
        exit 1
    fi

    exec wish8.6 $imunes -- $*
fi
