#!/bin/sh

if [ `id -u` -ne  0 ]; then
    echo "You must be root to run this script."
    exit 1
fi

if test -z "$*"; then
    echo "This script is a wrapper for apt-get, run it with arguments as you would run apt-get."
    echo "For additional info, run apt-get_imunes -h"
    exit 2
fi

vroot="imunes/vroot"

did=`docker run -d --net='bridge' $vroot`
docker exec $did apt-get update && docker exec -it $did apt-get "$@" && docker exec $did apt-get autoclean && docker exec $did apt-get autoremove && docker commit $did $vroot

docker rm -f $did
