#!/bin/sh

if [ `id -u` -ne  0 ]; then
    echo "You must be root to run this script."
    exit 1
fi

if test -z "$*"; then
    echo "This script is a wrapper for apt-get, run it with arguments as you would run apt-get."
    echo "For additional info, run apt-get_imunes -h"
    exit 2
fi

vroot="imunes/template"
ULIMITS="--ulimit nofile=10240:10240 --ulimit nproc=65356:65536"

if test $1 = "-i"; then
    vroot=$2
    shift 2
fi

echo "Changing docker image '$vroot'."

did=`docker run --detach --tty --net='bridge' $ULIMITS $vroot`
docker exec $did apt update && \
	docker exec -it $did apt "$@" && \
	docker exec -it $did apt clean && \
	docker exec -it $did apt autoclean && \
	docker exec -it $did apt autoremove && \
	docker commit $did $vroot

docker kill $did
docker rm -f $did
