#! /bin/sh 

if [ `id -u` -ne  0 ]; then
    echo "You must be root to run this script."
    exit 1
fi

command=`basename $0`

help() {
cat <<__END__

Command $command can be used to copy files to/from virtual images. 
Hostname is used instead of virtual images filesystem mount point.

Usage:

    $command [regular_cp_options] [vi_hostname]:filename [vi_hostname]:filename

If vi_hostname is a unique virtual image hostname on the system then
it is replaced with appropriate mount point and regular "cp" is called.
Hostname can be in the form: hostname or hostname@eid.
__END__
}

vi_name() {
  expid=`echo $1 | awk -F@ '{print $2}'`
  if test "a$expid" != "a"; then
    host=`echo $1 | cut -d@ -f1`
  else
    host=$1
    expid=""
  fi

  n=`jls -nq jid host.hostname path | awk -v h="host.hostname=$host" -v e="$expid" '$2 == h && $3 ~ e {print $1}' | wc -l`
  if test $n -gt 1; then
        echo "Error: $1 is not a unique name." >&2
        echo "It is used (at least) for nodes:" >&2
        jls | grep $1  >&2
        exit 1
  fi
  if test $n -eq 0; then
    echo Error: cannot find node named $1 >&2
    exit 2
  fi
  jls -nq jid host.hostname path | awk -v h="host.hostname=$host" -v e="$expid" '$2 == h && $3 ~ e {print $1}' | cut -d'=' -f2
}

if test $# -lt 2; then
    help >&2
    exit 1
fi

com="cp"
for a in $*
do
    arg=""
    if [ "x${a%-*}" = "x" ]
    then
        arg="$a"
    else
        hostname=${a%:*}
        filename=${a#*:}
        if [ "a$hostname" != "a$a" ]
        then
            image_name=`vi_name $hostname`
            test $? -ne 0 && exit 2
            arg="/var/imunes/`jls -h -j $image_name name | tail -n +2 | tr '.' '/'`/"
        fi
        arg="$arg$filename"
    fi
    com="$com $arg"
done
    
eval "$com"
stat=$?
if [ $stat -ne 0 ] ; then
    echo Check also: $command  >&2
fi
exit $stat

