#!/bin/sh

if [ `id -u` -ne  0 ]; then
    echo "You must be root to run this script."
    exit 1
fi

snapshot="vroot/vroot@clean"
union=`ls -A /var/imunes/vroot 2>/dev/null`
zfs=`zfs list | grep "vroot/vroot"`

if [ "$union" ]; then 
    VROOT="/var/imunes/vroot"
    zfs=""
elif [ "$zfs" ]; then 
    VROOT="/vroot/vroot"
else 
    echo "We couldn't detect any of the standard virtual node filesystems."
    echo "Please run the following to instantiate the filesystem:"
    echo "  # make vroot"
    exit 1
fi

cp /etc/resolv.conf $VROOT/etc
pkg_add $* -C $VROOT
if [ $? -ne 0 ]; then
    zfs=""
fi
rm $VROOT/etc/resolv.conf

if [ "$zfs" ]; then
    zfs destroy  "$snapshot"
    zfs snapshot "$snapshot"
fi
